image: golang:1.10

stages:
  - build
  - test

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - echo "${GOPATH}"
  - cp -r /builds/rfaulhaber /go/src/github.com/rfaulhaber
  - cd /go/src/github.com/rfaulhaber/force-data
  - dep ensure

build-project:
  stage: build
  script:
    - go build

test-project:
  stage: test
  script:
    - go test -v -cover ./...

