image: golang:1.10

stages:
  - build
  - test

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

build-project:
  stage: build
  script:
    - go build

test-project:
  stage: test
  script:
    - go test -v -cover ./...

