image: golang:1.10

stages:
	- build
	- test

before_script:
	- mkdir -p ${GOPATH}/src/${GO_PROJECT}
	- go get -u github.com/golang/dep/cmd/dep
	- cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
	- cd ${GOPATH}/src/${GO_PROJECT}	
	- dep ensure

build-project:
	stage: build
	script:
		- go build -v 

test-project:
	stage: test
	script:
		- go test -v -cover ./...
